### ISSUE TITLE
Use SelectorGadget's engine

### ISSUE THREAD

**Issue by cantino** [hijonathan/unsizzle#2]
Would you be interested in pulling in some of SelectorGadget's selection / rejection engine?  SG is all CoffeeScript at this point, built with Guard: https://github.com/cantino/selectorgadget/tree/master/lib/js/core

**Comment by cantino** [comment]
The SelectorGadget engine tries to guess a maximal selector that finds only the items you've selected, and none that you haven't.  I don't know if that would be helpful for you or not.

**Comment by hijonathan** [comment]
Totally get that, I just couldn't follow the codebase very well and am reluctant to bring in something I don't fully understand.

Check out the `faster` branch I've been working on. Way clearer imo and does the same thing. It even uses a similar selector weighting like you do in dom.coffee.

Honestly I'd love to use selector gadget instead of writing my own, but I'd need to have a better handle on what it does if I'm going to rely on it. The code, as it is, is way too confusing to follow.

Btw I took a look at some performance tests, and it looks like querySelectorAll is significantly faster than XPath lookups in all browsers. Have you found that not to be the case in your tests?
- Jonathan

**Comment by cantino** [comment]
Yea, understandable.  It could use some cleanup.
